### ISSUE TITLE
codecov fails in github actions

### ISSUE THREAD

**Issue by iapicca** [codecov/codecov-action#330] opened 2021-06-06 16:34 UTC
### backgrond

- my setup for codecov has worked well so far

   - you can regular updates with each pr commits [here][1]
   - I haven't change my repo settings

- as I've inadvertently pushed a folder that I wasn't supposed to, then I merged a [pr][2] to remove said folder

- here is my [codecov.yml ](https://github.com/iapicca/yak_packages/blob/master/codecov.yml)

### issue

- on the aforementioned last pr linked above the github action ci complained with the log below

```
  _____          _
 / ____|        | |
| |     ___   __| | ___  ___ _____   __
| |    / _ \ / _` |/ _ \/ __/ _ \ \ / /
| |___| (_) | (_| |  __/ (_| (_) \ V /
 \_____\___/ \__,_|\___|\___\___/ \_/
                              Bash-1.0.3


==> git version 2.31.1 found
==> curl 7.68.0 (x86_64-pc-linux-gnu) libcurl/7.68.0 OpenSSL/1.1.1f zlib/1.2.11 brotli/1.0.7 libidn2/2.2.0 libpsl/0.21.0 (+libidn2/2.2.0) libssh/0.9.3/openssl/zlib nghttp2/1.40.0 librtmp/2.3
Release-Date: 2020-01-08
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS brotli GSS-API HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM NTLM_WB PSL SPNEGO SSL TLS-SRP UnixSockets
==> GitHub Actions detected.
    Env vars used:
      -> GITHUB_ACTIONS:    true
      -> GITHUB_HEAD_REF:   remove-speedtest
      -> GITHUB_REF:        refs/pull/136/merge
      -> GITHUB_REPOSITORY: iapicca/yak_packages
      -> GITHUB_RUN_ID:     {{I'll keep this for myself}}
      -> GITHUB_SHA:        {{I'll keep this for myself}}
      -> GITHUB_WORKFLOW:   CI
->  Issue detecting commit SHA. Please run actions/checkout with fetch-depth > 1 or set to 0
    project root: .
    Yaml found at: codecov.yml
==> Running gcov in . (disable via -X gcov)
==> Python coveragepy not found
==> Searching for coverage reports in:
    + .
    -> Found 7 reports
==> Detecting git/mercurial file structure
==> Reading reports
    + ./packages/yak_tween/coverage/lcov.info bytes=2228
    + ./packages/yak_utils/coverage.lcov bytes=687
    + ./packages/yak_test/coverage.lcov bytes=339
    + ./packages/stub/coverage.lcov bytes=678
    + ./packages/yak_runner/coverage.lcov bytes=6429
    + ./packages/yak_widgets/coverage/lcov.info bytes=1444
    + ./packages/yak_error_handler/coverage.lcov bytes=1017
==> Appending adjustments
    https://docs.codecov.io/docs/fixing-reports
    + Found adjustments
==> Gzipping contents
        8.0K	/tmp/codecov.yP3SSF.gz
==> Uploading reports
    url: https://codecov.io
    query: branch=remove-speedtest&commit={{I'll keep this for myself}}
    &build={{I'll keep this for myself}}&build_url=http%3A%2F%2Fgithub.com%2Fiapicca%2Fyak_packages%2Factions%2Fruns%2F911981303&name=&tag=&slug=iapicca%2Fyak_packages&service=github-actions&flags=&pr=136&job=CI&cmd_args=

->  Pinging Codecov
https://codecov.io/upload/v4?package=bash-1.0.3&token=secret&branch=remove-speedtest&commit={{I'll keep this for myself}}&build={{I'll keep this for myself}}&build_url=http%3A%2F%2Fgithub.com%2Fiapicca%2Fyak_packages%2Factions%2Fruns%2F911981303&name=&tag=&slug=iapicca%2Fyak_packages&service=github-actions&flags=&pr=136&job=CI&cmd_args=
{'detail': ErrorDetail(string='Unable to locate build via Github Actions API. Please upload with the Codecov repository upload token to resolve issue.', code='not_found')}
404
==> Uploading to Codecov
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  5026  100   171  100  4855   1000  28391 --:--:-- --:--:-- --:--:-- 29220
100  5026  100   171  100  4855   1000  28391 --:--:-- --:--:-- --:--:-- 29220
    {'detail': ErrorDetail(string='Unable to locate build via Github Actions API. Please upload with the Codecov repository upload token to resolve issue.', code='not_found')}

```

 - the suggested fix is quite obscure to me

```
{'detail': ErrorDetail(string='Unable to locate build via Github Actions API. Please upload with the Codecov repository upload token to resolve issue.', code='not_found')}
```

### request

as I don't really want to run anything locally can someone help me to fix the issue
inside the CI

thank you

[stackoverflow question](https://stackoverflow.com/q/67861379/9836706)

  [1]: https://app.codecov.io/gh/iapicca/yak_packages
  [2]: https://github.com/iapicca/yak_packages/pull/136/

**Comment by bocklund** [comment] 2021-06-07 01:46
+1 

We are seeing this issue in [pycalphad](https://github.com/pycalphad/pycalphad/actions/workflows/test.yaml) where sometimes the uploads are successful and other times they are not, with no changes in our configuration. We have broken out the upload step for our different platforms into a different job within the GitHub Action, so we can confirm that it's isolated here.

We use the GitHub token, so rotating tokens as suggested in the SO question doesn't really apply.

**Comment by slarse** [comment] 2021-06-07 08:14
Uploads are failing sporadically across all of my public repositories (no token, but same error message). A couple of examples:

* [repobee/repobee](https://github.com/repobee/repobee/pull/919)
* [spoonlabs/sorald](https://github.com/SpoonLabs/sorald/pull/557)
* [KTH/spork](https://github.com/KTH/spork/pull/208)

**Comment by Matt-Yorkley** [comment] 2021-06-07 12:16
Same here, started ~2 days ago. Uploading the report to Codecov in the Github action fails 50% of the time, and the response code also seems to be non-zero, even though we're not using the `fail_ci_if_error` option, so the tests are reported as failed even if they pass.

**Comment by aahnik** [comment] 2021-06-07 12:19
Everything was fine before. Today I am experiencing this issue for my public repos. As far I know, public repos don't require a token.

One related side question.

My GitHub notifications are configured to notify me only when an action fails. I have **configured codecov action to not fail ci on error** of codecov.

```yaml
fail_ci_if_error: false
```

So, my ci will not fail. **but I still want to get notified when upload to codecov fails**, or any codecov issue occurs inside the gh action run. Is that possible?

**Comment by rowanseymour** [comment] 2021-06-07 15:46
Same here on our public repos (e.g. https://github.com/nyaruka/rapidpro/pull/3339/checks?check_run_id=2765067466). Haven't changed anything in the configurations. Really don't want to resort to `fail_ci_if_error: false` because it's important for us to know if reported coverage is correct.

**Comment by woop** [comment] 2021-06-07 16:31
We're also getting failures over here: https://github.com/feast-dev/feast/actions/runs/915501111. No changes from our side.

**Comment by freddyaboulton** [comment] 2021-06-07 18:31
We have also seen the same thing in evalml:

https://github.com/alteryx/evalml/pull/2256/checks?check_run_id=2766309621
https://github.com/alteryx/evalml/actions/runs/915203323
https://github.com/alteryx/evalml/runs/2764848236?check_suite_focus=true

Is there a plan for a fix from codecov? Any help would be appreciated! This started happening for us sometime today.

**Comment by slarse** [comment] 2021-06-08 12:30
This repo has version 1.0.2 of the bash uploader, but the latest one is 1.0.3. They've updated how an HTTP response is checked, so I'm guessing that's where we run into issues.

Using my own version of the codecov-action (with bash uploader 1.0.3), uploading seems to work again. For the time being, a  workaround is to just use the bash uploader directly, for example like so: https://github.com/SpoonLabs/sorald/pull/560/files

> Use at your own risk, I'm guessing they inlined the bash uploader into this action due to the recent security breach!

**Comment by thomasrockhu** [comment] 2021-06-08 15:12
@slarse thanks for pointing this out. However, the changes between `1.0.2` to `1.0.3` are only for a very small subset of users. We'll be upgrading the action today regardless.

For everyone else, thanks again for raising this issue. It looks like this is a problem with our ability to access GitHub and is causing our API calls to be rate-limited. We recommend using the [GitHub app integration](https://github.com/apps/codecov) to alleviate the issue. If you are using the integration and are still getting issues, please ping me back here.

**Comment by frett** [comment] 2021-06-08 15:15
> For everyone else, thanks again for raising this issue. It looks like this is a problem with our ability to access GitHub and is causing our API calls to be rate-limited. We recommend using the [GitHub app integration](https://github.com/apps/codecov) to alleviate the issue. If you are using the integration and are still seeing this problem, please ping me back here or on our [community boards](https://community.codecov.com)

We are currently using the GitHub app integration for https://github.com/CruGlobal/kotlin-mpp-godtools-tool-parser and seeing this issue. (at least I'm pretty sure we are because that repo is currently enabled for the App configuration)

**Comment by catthehacker** [comment] 2021-06-08 15:15
@thomasrockhu one repo I help maintaining has installed GH app but still fails from what I see
![image](https://user-images.githubusercontent.com/31106839/121211756-09740e00-c87d-11eb-8882-cdf41669d663.png)
https://github.com/nektos/act/runs/2775230988?check_suite_focus=true#step:7:57

**Comment by slarse** [comment] 2021-06-08 15:29
@thomasrockhu Thanks for dropping in!

I'm using the GitHub app for all of the projects I listed in my original comment (see https://github.com/codecov/codecov-action/issues/330#issuecomment-855708518). I even tried reinstalling it for https://github.com/repobee making sure that it was enabled for all repositories in the organization, but it didn't solve the problem.

**Comment by thomasrockhu** [comment] 2021-06-08 15:43
Got it, looks like there is another issue. Our product team is looking into it, and I'll update here as soon as I have any news. Thanks for your patience everyone.

**Comment by thomasrockhu** [comment] 2021-06-08 15:47
As a sidenote, we released `v1.5.1` which contains the latest version of the bash uploader `1.0.3` (as well as dependency updates and small fixes). I don't expect this to resolve the underlying issue but just wanted everyone to be aware of the change.

**Comment by thomasrockhu** [comment] 2021-06-08 16:47
We've made some changes to our infrastructure which should help alleviate the problem. I don't believe that it will drop incidents to 0, but we are continuing to work on this issue.

**Comment by ktdreyer** [comment] 2021-06-08 20:36
GitHub Actions are working again for me. Thanks!

**Comment by thomasrockhu** [comment] 2021-06-08 21:37
We are finalizing some changes and we expect this to be resolved in the next hour. I will close this out tomorrow if there are no more outstanding issues. Thanks everyone for being patient!

**Comment by filbranden** [comment] 2021-06-09 00:26
I'm still running into it. Just tried to do a force push on a PR and had the same error.

https://github.com/igrigorik/vimgolf/pull/336/checks?check_run_id=2779188700

I'm happy to help debugging if needed, but unfortunately the comments here (and the error message) don't seem to give enough context to help try figure out what's wrong...

**Comment by filbranden** [comment] 2021-06-09 00:40
Looks like the problem is with v1.5.1, possibly with commit c9d0b8155c1a7ca4f072a580cdcb3df48a9137a4.

Running with v1 fails:
https://github.com/igrigorik/vimgolf/pull/336/checks?check_run_id=2779188700

The command line is:

```
/usr/bin/bash codecov.sh -n  -F  -Q github-action-[object Object] -f ./coverage/coverage.xml -C 52664fe31e7d5982747daf349365a2702b34c613
```

Running with v1.5.0 succeeds:
https://github.com/igrigorik/vimgolf/pull/336/checks?check_run_id=2779237328

The command line is:

```
/usr/bin/bash codecov.sh -n  -F  -Q github-action -f ./coverage/coverage.xml -C fdcda86a7ca2c721824bfdc237228ae6b7c6050e
```

Not sure what's up with that `[object Object]`, but it might be related to the failure... (?)

In any case, I hope this report here is helpful.

**Comment by filbranden** [comment] 2021-06-09 01:06
Actually, I'm fairly sure problem is with the follow up commit b8f68524afdfa99b19eb050a7facfe1341594954 ("lint"), which uses a new-style export for the version (`export default VERSION`) but then uses an old-style require (`const VERSION = require('./version')`) to load it.

Switching to an actual import (`import VERSION from './version'`) would likely fix it.

**Comment by thomasrockhu** [comment] 2021-06-09 01:28
Sorry about that, I've opened a PR and I look to deploy in the next hour.

**Comment by thomasrockhu** [comment] 2021-06-09 02:06
Hi all, I have deployed `1.5.2` which should fix the above issue. I will continue to keep this open at least for the next 24 hours if there are no other issues.

**Comment by dword-design** [comment] 2021-06-09 09:24
Still the issue for me that regenerating the token fixes it shortly but then the problem reappears.

**Comment by xydesa** [comment] 2021-06-09 15:19
v1.5.2 seems to have fixed my problem. Thank you!

**Comment by thomasrockhu** [comment] 2021-06-09 15:40
@dword-design you might have been at the tail end of some infrastructure changes we made to help with this issue. Are you still running into problems?

**Comment by dword-design** [comment] 2021-06-09 17:30
@thomasrockhu Seems to be working now. Thanks for the quick fix!

**Comment by AenBleidd** [comment] 2021-06-09 23:48
It fails again

**Comment by thomasrockhu** [comment] 2021-06-11 13:57
Hi @AenBleidd, can you open a ticket in our [community boards](https://community.codecov.io)? I believe the root cause of this particular issue is different and has been fixed. I would like to get some more information about what's causing the issue for you.

**Comment by thomasrockhu** [comment] 2021-06-11 13:57
Aside from that, I'm going to close this issue as it looks to be resolved. Thanks again, everyone.

**Closed by thomasrockhu** 2021-06-11 13:57 UTC

**Comment by lmmx** [comment] 2021-07-29 19:26
Just encountered this 3x in a row, version is 1.5.2 (which some above were saying contained a bugfix)
