### ISSUE TITLE
Is there a way to make this work with a PR from a fork

### ISSUE THREAD

**Issue by kevinbarabash** [codecov/codecov-action#29] opened 2019-10-20 22:29 UTC
I have the codecov action working for PRs that I create in my repo, but it doesn't work for external contributors.  I appears that `secrets.CODECOV_TOKEN` isn't getting set for external PRs.  Is there anyway to get codecov working with PRs from forks?

**Comment by tenmozes** [comment] 2019-10-23 16:33
same problem as in https://github.com/codecov/codecov-action/issues/22

**Comment by tenmozes** [comment] 2019-10-25 09:25
@ibrahim0814 could you please tell about the future plans and this issue?

**Comment by kefranabg** [comment] 2019-11-10 10:56
Regarding security, it would be bad to allows forked PRs to access your GitHub secrets.

**Comment by tenmozes** [comment] 2019-11-10 12:28
Ok do we have suitable solution how avoid secret leaking and have tool which works?

**Comment by ibrahim0814** [comment] 2019-11-11 18:11
Hi all,

Currently there's no way to make this Action work for forks and PRs from other contributors since secrets are only available to the owner of the repository. We are looking to add tokenless support for Actions once GitHub releases a public API for Actions that would subsequently fix those issues. For context, we call the API during the upload process to verify repository details if no token is provided. However, until an API released, our hands are strapped. 

I apologize for the limited capabilities on this particular Action right now, but we're definitely looking for ways to improve it in the near future

Ib

**Comment by hugovk** [comment] 2019-11-20 16:43
Please give this a 👍or comment to let GitHub know:

* https://github.community/t5/GitHub-Actions/Make-secrets-available-to-builds-of-forks/m-p/30678/highlight/true#M508

**Comment by anuraaga** [comment] 2019-12-02 07:31
Hi @ibrahim0814 - found this issue looking into adding a codecov action to a public repo. You mention a dependency on a public Actions API, but I think it should be possible with current APIs. All builds have a temporary access token with read permissions for forks

https://help.github.com/en/actions/automating-your-workflow-with-github-actions/authenticating-with-the-github_token#permissions-for-the-github_token

So it should be possible to forward that to a codecov server and check whether the repository can be accessed by the token using current APIs such as https://developer.github.com/v3/repos/#list-your-repositories. 

If a user wanted to make sure codecov didn't get a token with write permissions, they can tweak their workflow to use the default `GITHUB_TOKEN` for pull requests and a custom token scoped to read-only for pushes.

Not the greatest UX, but I think it's better than not working at all :) I'm not sure how the current out-of-box integrations for Travis / Appveyor work but I guess it's a similar process?

**Comment by hugovk** [comment] 2020-01-08 08:07
If you hardcode the token, builds on forks (even if no PR is made) will be sent to the pytest's own Codecov, which clutters up the logs somewhat, and fork users cannot see their own coverage before creating PRs.

We temporarily worked around this (https://github.com/python-pillow/Pillow/pull/4266) by adding a "Prepare coverage token" step before the "Upload coverage" step:

```yml
    - name: Prepare coverage token
      if: success() && github.repository == 'python-pillow/Pillow'
      run: cp .github/codecov-upstream.yml .codecov.yml

    - name: Upload coverage
      if: success()
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        name: ${{ matrix.os }} Python ${{ matrix.python-version }}
```

https://github.com/python-pillow/Pillow/blob/ef4a0b2f4c9346db37140f102e80068abc280167/.github/workflows/test.yml#L94-L103

[`.github/codecov-upstream.yml`](https://github.com/python-pillow/Pillow/blob/ef4a0b2f4c9346db37140f102e80068abc280167/.github/codecov-upstream.yml) is the same as [`.codecov.yml`](https://github.com/python-pillow/Pillow/blob/ef4a0b2f4c9346db37140f102e80068abc280167/.codecov.yml), except it has the hardcoded upstream token for Codecov.

If you do want GHA coverage from your own fork's builds sent to your own fork's Codecov, fetch your token from https://codecov.io/gh/my-username/pytest/settings and add it as `CODECOV_TOKEN` at https://github.com/my-username/pytest/settings/secrets.

**Comment by ishepard** [comment] 2020-02-03 09:57
FYI: [https://github.blog/changelog/2020-01-27-github-actions-api-beta/](https://github.blog/changelog/2020-01-27-github-actions-api-beta/)

There finally seems to be an API! And according to [this comment](https://community.codecov.io/t/whitelist-github-action-servers-to-upload-without-a-token/491/15), codecov is working on a tokenless upload 😃

**Comment by ibrahim0814** [comment] 2020-02-03 18:02
Yes, can confirm. We’re working to release that feature as quickly as possible :)

**Comment by emersonknapp** [comment] 2020-02-05 01:38
@ibrahim0814 that's great news! is there a separate tracking issue for that work, or is this the place to watch for updates?

**Comment by SVilgelm** [comment] 2020-02-09 00:33
@ibrahim0814 Any assumptions about the date when it can be implemented?

**Comment by SVilgelm** [comment] 2020-02-17 11:56
@ibrahim0814 It's pretty urgent question, do you have any updates?

**Comment by ibrahim0814** [comment] 2020-02-20 21:59
Hi all, we're still on it. It's a priority to ship this out right now, so definitely expect this within the next five business days

**Comment by SVilgelm** [comment] 2020-02-20 22:00
@ibrahim0814 thank you so much for the update!!!!!

**Comment by SVilgelm** [comment] 2020-03-04 19:07
@ibrahim0814 Hi, is there any updates?

**Comment by ibrahim0814** [comment] 2020-03-05 00:17
Hi all,

We’ve officially deployed tokenless for GitHub Actions as of today (2/4)! I’m sorry about the long wait time - there were lots of components on the backend that needed to be synchronized for this to come together. 

You should now be able to successfully make Actions for PRs from a forked repository

Happy (tokenless) uploading y'all!

Ib

**Comment by nicolo-ribaudo** [comment] 2020-03-05 00:44
@ibrahim0814 I noticed that the coverage reported for PRs is lower than the one reported after merging them. This has been happening for every PR since coverage from GH actions started working (btw, thank you very much! :heart:).
Should I report it in a new issue, or could it be a problem in our action config?

Example: https://github.com/babel/babel/pull/11207 vs https://github.com/babel/babel/commit/a12001a0f930b41a4df6d1f9af3f442a721114ce.

**Comment by facelessuser** [comment] 2020-03-05 00:45
@ibrahim0814 Is there documentation about this? Or do you just use the action as always without a token and it will just work?

**Comment by ibrahim0814** [comment] 2020-03-05 00:52
@nicolo-ribaudo I would post this issue on our community forum [here](https://community.codecov.io/.) to get a response from one of our support engineers. This doesn't seem like it would be an issue in your action config

**Comment by ibrahim0814** [comment] 2020-03-05 01:16
I plan on releasing a new version of this Action within the next few hours. There seem to be some bugs that need to be ironed out for tokenless @nicolo-ribaudo. However, I can confirm that our bash uploader works fine

**Comment by ibrahim0814** [comment] 2020-03-05 07:03
Hi y'all,

Just released a new version of this Action. I added the right environment variables such that tokenless uploads should now work correctly with this Action. If you already use the major version tag `@v1` then the updates should automatically be reflected for you the next time you run your workflows!

We've come a long way since the start of this issue and I appreciate everyone's patience and input. We're a small team here at Codecov and I'm the only person in charge of maintaining this repository and our tokenless infrastructure so without this community's support, none of this would be remotely possible ❤️ 

Please let me know if everything is working fine and post below if you guys encounter issues. Otherwise, I plan on closing this issue tomorrow :) 

Ib

**Comment by harupy** [comment] 2020-03-05 07:11
@ibrahim0814 
This is awesome! Just out of curiosity. How did you make the action tokenless with the GitHub Actions API?

**Comment by ibrahim0814** [comment] 2020-03-05 15:27
@harupy Sure, glad to explain! If I understood your question correctly, you want to know how we make tokenless uploads work via the Actions API, right? If so here's a broad overview of how it all works:  

Whenever you upload a report to Codecov, we look to validate it somehow, usually in the form of a token. However, if a CI provider has a robust enough API (and the repository is public) we can also validate it through the provider's API. 

The first step in this process is actually identifying the build - we do this by extracting certain environment variables whenever your workflow runs. GitHub provides [these environment variables](https://help.github.com/en/actions/configuring-and-managing-workflows/using-environment-variables#default-environment-variables) by default, including `GITHUB_RUN_ID` which is a unique number identifying the current build. Codecov then picks up these default variables through this Action and uses them to construct a valid API url which can then be used to retrieve detailed information about the current build. For example, [here's a workflow](https://api.github.com/repos/swinton/actions-playground/actions/runs/32402849) that ran on a public repository for which you can see detailed build information. 

This API response is then parsed and we look at several fields to make sure that the arguments we *initially received* match up with the information from the Actions API. For example, the commit sha in the API response should match up with the commit sha value we received from those default environment variables I mentioned above + the build should be in-progress/not stale and the repository slug should be the same etc. If all of these checks come through okay, we can be very certain that the upload can be validated. 

For this Action, before I released `v.1.0.6` today, it wasn't passing the run id environment variable to the bash uploader, so the build could not be properly identified. This subsequently messed up the API call to GitHub and caused some issues

Hope that helps to clear things up. Let me know if you have any other questions or concerns!

Ib

**Comment by ibrahim0814** [comment] 2020-03-06 00:05
Closing this issue now!

**Closed by ibrahim0814** 2020-03-06 00:05 UTC

**Comment by harupy** [comment] 2020-03-06 01:33
@ibrahim0814 Thank you for the clear explanation! I perfectly understand.

**Comment by smorimoto** [comment] 2020-10-14 05:18
FYI: We can do it this way without doing extra hacks now.
https://github.blog/2020-08-03-github-actions-improvements-for-fork-and-pull-request-workflows/

**Comment by s-weigand** [comment] 2020-10-14 06:48
@smorimoto thanks for sharing 😄
