### ISSUE TITLE
Implement tokenless mode

### ISSUE THREAD

**Issue by webknjaz** [codecov/codecov-action#55] opened 2020-02-12 13:09 UTC
Newly released API should make this possible: https://github.blog/2020-02-06-manage-secrets-and-more-with-the-github-actions-api/

**Comment by SVilgelm** [comment] 2020-02-20 21:51
Duplicate of the #29

**Comment by ibrahim0814** [comment] 2020-03-05 00:34
Hi @webknjaz!

Thanks for bringing this up. I've addressed this in #29, but good news is that we just deployed tokenless for GitHub Actions today! Happy uploading!

Ib

**Closed by ibrahim0814** 2020-03-05 00:34 UTC
