### ISSUE TITLE
Strange package name in curl uploading url

### ISSUE THREAD

**Issue by ibmibmibm** [codecov/codecov-action#341] opened 2021-06-08 22:49 UTC
After [this commit](https://github.com/codecov/codecov-action/commit/b8f68524afdfa99b19eb050a7facfe1341594954), the package name become strange, makes curl failed to upload
```
==> Uploading to Codecov
curl: (3) bad range in URL position 53:
https://codecov.io/upload/v2?package=github-action-[objectObject]-1.0.3&token=***&...
HTTP 500
Error: Codecov failed with the following error: The process '/usr/bin/bash' failed with exit code 1
```

**Comment by thomasrockhu** [comment] 2021-06-08 22:55
This is me, sorry will push a fix tonight.

**Comment by filbranden** [comment] 2021-06-09 01:07
Probably duplicate of #330. See my last comments there with the source of the issue...

**Comment by thomasrockhu** [comment] 2021-06-09 02:05
Thanks again @filbranden. Closing in favor of https://github.com/codecov/codecov-action/issues/330

**Closed by thomasrockhu** 2021-06-09 02:05 UTC
