### ISSUE TITLE
Tokenless upload broken

### ISSUE THREAD

**Issue by ph-fritsche** [codecov/codecov-action#103] opened 2020-08-04 13:35 UTC
Uploading coverage for public repository fails with
```
->  Pinging Codecov
https://codecov.io/upload/v4?package=bash-20200728-9fb7d93&token=secret&branch=master&commit=8c34379a3a8e21a12a6b8306d074212cc7ec55ca&build=&build_url=&name=&tag=&slug=ph-fritsche%2Fliform-material&service=&flags=&pr=&job=&cmd_args=f,n,F,Z
HTTP 400
Please provide the repository token to upload reports via `-t :repository-token`
##[error]Codecov failed with the following error: The process 'bash' failed with exit code 1
```

![image](https://user-images.githubusercontent.com/39068198/89299430-ec701c80-d666-11ea-83b3-165cacbbfd1d.png)

**Comment by thomasrockhu** [comment] 2020-08-04 13:43
Closing as a duplicate of https://github.com/codecov/codecov-action/issues/102

**Closed by thomasrockhu** 2020-08-04 13:43 UTC
