### ISSUE TITLE
No CI provider detected. Github actions env var issue.

### ISSUE THREAD

**Issue by dwillist** [codecov/codecov-action#102] opened 2020-08-03 21:04 UTC
Seeing a new failure when running this action, with the output "No CI provider detected". From [this line](https://github.com/codecov/codecov-bash/blob/9fb7d93ac9469a80807e239097a013fb8eb61032/codecov#L790) in the script.
 
Seems like the assumptions around which github environment variables are available to this action need to be updated.
Maybe [here](https://github.com/codecov/codecov-action/blob/07127fde53bc3ccd346d47ab2f14c390161ad108/index.js#L61)?

Full output:
```
Run codecov/codecov-action@v1
  with:
    file: ./out/tests/coverage-unit.txt
    flags: unit,os_macos
    fail_ci_if_error: true
  env:
    PACK_BIN: pack
    NO_DOCKER: true
    PACK_VERSION: 0.0.0
    GOROOT: /Users/runner/hostedtoolcache/go/1.14.6/x64
    GOPATH: /Users/runner/go
    GITHUB_ACTION: 
    GITHUB_RUN_ID: 193840501
    GITHUB_REF: refs/pull/769/merge
    GITHUB_REPOSITORY: buildpacks/pack
    GITHUB_SHA: bc1d7f725f8b665f2535eaaf4a49eea91954c57c
    GITHUB_HEAD_REF: 253_inspect_builder_enhancement

x> No CI provider detected.
    Testing inside Docker? http://docs.codecov.io/docs/testing-with-docker
    Testing with Tox? https://docs.codecov.io/docs/python#section-testing-with-tox
    project root: .
    Yaml found at: codecov.yml
    -> Found 1 reports
==> Detecting git/mercurial file structure
==> Reading reports
    + ./out/tests/coverage-unit.txt bytes=149464
==> Appending adjustments
    https://docs.codecov.io/docs/fixing-reports
    + Found adjustments
==> Gzipping contents
==> Uploading reports
    url: https://codecov.io
    query: branch=&commit=1a28f9f0261c2e81d06fca6e6791e22d6ce510e0&build=&build_url=&name=&tag=&slug=buildpacks%2Fpack&service=&flags=unit,os_macos&pr=&job=&cmd_args=f,n,F,Z
->  Pinging Codecov
https://codecov.io/upload/v4?package=bash-20200728-9fb7d93&token=secret&branch=&commit=1a28f9f0261c2e81d06fca6e6791e22d6ce510e0&build=&build_url=&name=&tag=&slug=buildpacks%2Fpack&service=&flags=unit,os_macos&pr=&job=&cmd_args=f,n,F,Z
HTTP 400
Please provide the repository token to upload reports via `-t :repository-token`
##[error]Codecov failed with the following error: The process 'bash' failed with exit code 1
```

**Comment by LCaparelli** [comment] 2020-08-03 21:20
Hitting the same [here](https://github.com/m88i/nexus-operator/pull/135). Looks like it requests a token because it couldn't detect the CI environment (if I'm reading [this](https://docs.codecov.io/docs/about-the-codecov-bash-uploader) correctly, GH actions shouldn't need tokens).

Can we work around the issue by setting some environment variable within the action?

**Comment by thomasrockhu** [comment] 2020-08-03 23:21
@LCaparelli, I forked your project [here](https://github.com/thomasrockhu/nexus-operator/pull/1/checks?check_run_id=942658060), and I'm not seeing any issues with finding the CI environment variables. Would you be able to re-run and see if you are still getting this issue?

**Comment by thomasrockhu** [comment] 2020-08-03 23:31
@dwillist same thing, I forked [here](https://github.com/thomasrockhu/pack/runs/942674312?check_suite_focus=true), and it looks to be ok. I'm hoping this is some strange GitHub issue, but please let me know if you can still reproduce.

**Comment by LCaparelli** [comment] 2020-08-03 23:33
@thomasrockhu thanks for the prompt response! I just re-triggered the checks and I'm still running into the same issue :confused: 

In case you want to [have a look](https://github.com/m88i/nexus-operator/pull/135/checks?check_run_id=942686169).

**Comment by thomasrockhu** [comment] 2020-08-03 23:45
@LCaparelli, this is quite strange. I was wondering if you could do two things

(1) Could you add this [line](https://github.com/thomasrockhu/nexus-operator/pull/1/files#diff-90829e76e906f1c73140c7ded7e1b268R66-R67) to your workflow and see what the output is? The bash script uses `GITHUB_ACTION` to determine if it's using Actions. 
(2) Could you try using the bash uploader with this [line](https://github.com/thomasrockhu/nexus-operator/pull/1/files#diff-90829e76e906f1c73140c7ded7e1b268R75-R76) and seeing if it goes through?

**Comment by LCaparelli** [comment] 2020-08-04 00:04
@thomasrockhu this is a weird one for sure. Added those lines, it seems that `$GITHUB_ACTION` isn't set, it produced no output. [Here](https://github.com/m88i/nexus-operator/pull/135/checks?check_run_id=942742666).

Using the bash uploader rendered the exact same result (I'm guessing the root cause is the unset env var).

**Comment by eddynaka** [comment] 2020-08-04 01:31
Hi all, do we have a workaround to make this work?
Thank you.

**Comment by dwillist** [comment] 2020-08-04 01:34
Same results as @LCaparelli. The only way I could get things to work was manually re-building the action and hard-coding the value of `GITHUB_ACTION` in the implementation [here](https://github.com/dwillist/codecov-action/blob/1a088b606bc6f1b37ec69f258dc693be0e5e85ce/index.js#L62). Guess this is starting to look more like an issue with the runner failing to set the `GITHUB_ACTION` environment variable.

Looks like a potential workaround would be to change the conditional [here](https://github.com/codecov/codecov-bash/blob/9fb7d93ac9469a80807e239097a013fb8eb61032/codecov#L790) to use `GITHUB_ACTIONS` rather than `GITHUB_ACTION`. Both should be set by the action as documented [here](https://docs.github.com/en/actions/configuring-and-managing-workflows/using-environment-variables#default-environment-variables)

**Comment by thomasrockhu** [comment] 2020-08-04 02:00
I'm wondering if https://github.com/actions/runner/pull/593 has anything to do with it. It seems to have been released [5 days ago](https://github.com/actions/runner/blob/38f816c2ae2a8c441feb8df3e1108ff245f1c8a7/releaseNote.md)

**Comment by thomasrockhu** [comment] 2020-08-04 02:05
Hi @eddynaka, this seems to be broken from the [GitHub side](https://github.com/actions/runner/issues/635). We will work on a fix from our side, sorry for the breakage of service here.

**Comment by thomasrockhu** [comment] 2020-08-04 13:17
We are expecting this to be resolved by 10AM ET as documented by [GitHub](https://github.community/t/github-action-environment-variable-missing-breaking-issue/125913)

**Comment by LCaparelli** [comment] 2020-08-04 14:47
@thomasrockhu back to working again, thank you very much for your assistance! :-)

**Comment by thomasrockhu** [comment] 2020-08-04 15:08
Looks like this has been solved, thanks everyone!

**Closed by thomasrockhu** 2020-08-04 15:08 UTC

**Comment by potiuk** [comment] 2020-08-04 16:23
Yep. Works! Thanks everyone! https://codecov.io/github/apache/airflow/commit/304b17532b0672a4947df74464cd8d7a8c68bf3e
